<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ArasUpgradeOrchestrator.Core/ArasUpgradeOrchestrator.Core.csproj" />
    <ProjectReference Include="../../tools/ArasUpgradeOrchestrator.CoreTree.Cli/ArasUpgradeOrchestrator.CoreTree.Cli.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
