$ErrorActionPreference = 'Stop'
$caseRoot = 'K:\70.ArasUpgradeCases'
$caseName = [string]::Concat(([int[]](33455,27954) | ForEach-Object { [char]::ConvertFromUtf32($_) }))
$pending = '<' + [string]::Concat(([int[]](24453,25552,20379) | ForEach-Object { [char]::ConvertFromUtf32($_) })) + '>'
$casePath = Join-Path $caseRoot $caseName
$inputs = @(
 @{Id='ootb-11sp9';Version='11.0 SP9';Tree=(Join-Path $casePath 'core-tree\inputs\ootb-11sp9\tree');Evidence=(Join-Path $casePath 'core-tree\inputs\ootb-11sp9\evidence')},
 @{Id='ootb-r38';Version='R38';Tree=(Join-Path $casePath 'core-tree\inputs\ootb-r38\tree');Evidence=(Join-Path $casePath 'core-tree\inputs\ootb-r38\evidence')}
)
function Rel([string]$t,[string]$f){$a=[IO.Path]::GetFullPath($t).TrimEnd([char]92);$b=[IO.Path]::GetFullPath($f);$p=$a+[char]92;if(-not $b.StartsWith($p,[StringComparison]::OrdinalIgnoreCase)){throw 'File outside Tree'};return $b.Substring($p.Length).Replace([char]92,[char]47)}
function HashFile([string]$p){$sha=[Security.Cryptography.SHA256]::Create();$s=[IO.File]::OpenRead($p);try{return ([BitConverter]::ToString($sha.ComputeHash($s))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose();$sha.Dispose()}}
$outs=@();foreach($i in $inputs){foreach($n in @('version-primary.md','integrity.md','integrity.sha256','source-provenance.md')){$outs+=Join-Path $i.Evidence $n}}
foreach($i in $inputs){if(-not(Test-Path -LiteralPath $i.Tree -PathType Container)){throw "Missing Tree: $($i.Tree)"};if(-not(Test-Path -LiteralPath (Join-Path $i.Tree 'Innovator\Client') -PathType Container)){throw 'Missing Client'};if(-not(Test-Path -LiteralPath (Join-Path $i.Tree 'Innovator\Server') -PathType Container)){throw 'Missing Server'};if(-not(Test-Path -LiteralPath $i.Evidence -PathType Container)){throw 'Missing Evidence'}}
foreach($o in $outs){if(Test-Path -LiteralPath $o){throw "Refusing overwrite: $o"}}
$enc=[Text.UTF8Encoding]::new($true)
foreach($i in $inputs){$files=@(Get-ChildItem -LiteralPath $i.Tree -Recurse -File|Sort-Object FullName);$lines=New-Object Collections.Generic.List[string];foreach($f in $files){$lines.Add((HashFile $f.FullName)+'  '+(Rel $i.Tree $f.FullName))};$iom=Join-Path $i.Tree 'Innovator\Server\bin\IOM.dll';$v=(Get-Item -LiteralPath $iom).VersionInfo;$now=(Get-Date).ToString('o');[IO.File]::WriteAllText((Join-Path $i.Evidence 'integrity.sha256'),(($lines -join [Environment]::NewLine)+[Environment]::NewLine),$enc);[IO.File]::WriteAllText((Join-Path $i.Evidence 'version-primary.md'),("# Version Evidence`r`n`r`n- Input: $($i.Id)`r`n- Product version: $($i.Version)`r`n- Service Pack: SP9 (provided by case parameters; evidence pending)`r`n- Edition: Enterprise (case default; installation edition not separately identified)`r`n- IOM.dll FileVersion: $($v.FileVersion)`r`n- IOM.dll ProductVersion: $($v.ProductVersion)`r`n- IOM.dll path: $iom`r`n- Build: $pending`r`n- Hotfix: $pending`r`n- Collector: BCO\kenny`r`n- Collection time: $now`r`n- Manual confirmation: BCO\kenny (confirmation date and scope: $pending)`r`n"),$enc);[IO.File]::WriteAllText((Join-Path $i.Evidence 'integrity.md'),("# Integrity Evidence`r`n`r`n- Input: $($i.Id)`r`n- Tree root: $($i.Tree)`r`n- Collection time: $now`r`n- Collector: BCO\kenny`r`n- File count: $($files.Count)`r`n- SHA-256 list: $(Join-Path $i.Evidence 'integrity.sha256')`r`n- Method: SHA-256 over files sorted by verified relative path`r`n- Formal Build: $pending`r`n"),$enc);[IO.File]::WriteAllText((Join-Path $i.Evidence 'source-provenance.md'),("# Source Provenance`r`n`r`n- Input: $($i.Id)`r`n- Destination: $($i.Tree)`r`n- Original source location: $pending`r`n- Copy or export time: $pending`r`n- Copy or export method: Export (default reference; confirm actual method)`r`n- Operator: BCO\kenny`r`n- Manual confirmation: $pending`r`n"),$enc);Write-Output "$($i.Id): files=$($files.Count); hashes=$($lines.Count)"}
